# Based on the conda-forge appveyor script.
skip_commits:
  message: /^Merge pull request /

environment:
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script interpreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  # Workaround for https://github.com/conda/conda-build/issues/636
  PYTHONIOENCODING: "UTF-8"

  matrix:
    # Note: Because we have to separate the py2 and py3 components due to compiler version, we have a race condition for non-python packages.
    # Not sure how to resolve this, but maybe we should be tracking the VS version in the build string anyway?
    - TARGET_ARCH: "x86"
      CONDA_PY: "27"
      PY_CONDITION: "python >=2.7,<3"
      CONDA_INSTALL_LOCN: "C:\\Miniconda"
    - TARGET_ARCH: "x86"
      CONDA_PY: "35"
      PY_CONDITION: "python >=3.5,<3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35"
    - TARGET_ARCH: "x64"
      CONDA_PY: "27"
      PY_CONDITION: "python >=2.7,<3"
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "35"
      PY_CONDITION: "python >=3.5,<3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "36"
      PY_CONDITION: "python >=3.6,<3.7"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "37"
      PY_CONDITION: "python >=3.7,<3.8"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable (which is used by CMD_IN_ENV).
platform:
  - x64

install:
  # Use the pre-installed Miniconda for the desired arch
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: python --version
  - cmd: conda config --add channels conda-forge
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes --quiet obvious-ci
  - cmd: conda install --yes --quiet obspy pytest flake8 colorama h5py nose dill prov
  - cmd: conda list

# Skip .NET project specific build phase.
build: off

test_script:
  - "%CMD_IN_ENV% python setup.py develop"
  - "python -m pyasdf.tests"
